language: generic
sudo: required
services:
  -docker


  before_install:
    - docker build -t scottshrout/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true scottshrout/docker-react npm run test
  
